# Site settings
title: Shared IT, Inc.
email: jesse@sharedit.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://github.sharedit.com" # the base hostname & protocol for your site
github_username:  clarkguru
markdown: redcarpet
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
sass:
    sass_dir: assets/css
    style: nested
